### PR TITLE
Soot

### PR DESCRIPTION
**Pull request by Jianchu**
added two other tools (checker-framework and checker-framework-inference) that could be invoked by capture_javac.py. Argument for selecting tool is "-t". 
Is it good to rename the tool from soot_runner to a more generic name?

### CODE REVIEW

**Comment by tim-mccarthy** [comment]
Merged. I'll leave the decision on what to name the tool to someone else (e.g. @martinschaef).

**Comment by martinschaef** [comment]
yes ... sootrunner is a bit too specific ;) any suggestions? Something that gives a hint that this guy records the javac calls in a build.

**Comment by wmdietl** [comment]
The tool is tracing javac calls and then executing one of the three other tools.
capture_javac.py is also misleading, as it doesn't do the capturing at all.
Some names for brainstorming:
analyze-javac
do-like-javac
substitute4javac

All not very convincing...

**Comment by martinschaef** [comment]
I like do-like-javac ... maybe without the hyphens (should be underscores, since its python), but it sounds very unpretentious and straight-forward ... but then again, I'll follow whatever you guys want. @tim-mccarthy, you are the lead, you decide.

**Comment by wmdietl** [comment]
Can we settle on a name?
What is the point of the two separate branches?
A stable name would make using this tool in other projects easier.

**Comment by tim-mccarthy** [comment]
do-like-javac seems OK to me.
I was also thinking of something along the lines of a coffee strainer or
filter, but if people think that's too cute/esoteric, do-like-javac is fine.

I'll rename it tomorrow.

**Comment by wmdietl** [comment]
Ping about this.

**Comment by tim-mccarthy** [comment]
I made the change a few days ago.

**Comment by wmdietl** [comment]
Do you mind merging this into master? It's only in the "soot" branch.

**Comment by tim-mccarthy** [comment]
Done.

**Pull request merged**
